version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - wp_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
      volumes:
       - www_data:/var/www/html/wp-content
     expose:
      - 80
    #  ports:
    #    - "8080:80"
     restart: always
     environment:
       VIRTUAL_HOST: www.opoeic.me, opoeic.me
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    wp_db_data:
    www_data:

networks:
  default:
    external:
      name: nginx-proxy